/*
    This is a configuration script. This script performs any initialization that needs to happen
    before the server is launched. That includes:

    - Creating a .env file that combines env variables from env.production.local with user-set env variables
    - Creating a new database file (if desired)
    - Deciding whether the application is run in test mode or production mode

    When the application is run in test mode, the database is populated with dummy data.
    When the application is run in production mode, the database is populated with data from the client side.

    This script accepts the following command line flags:

    -test   ["true" to populate database with test data | "false" to populate database from the client side]
    -db     [databaseFileName] if you want to re-initialize (i.e. clear) the database

    
    (1) To create a new database and populate it with test data, run
        > node config.js -test true -db myDatabase.db
    
    (2) To create a new database and read data from the client side, run
        > node config.js -test false -db myDatabase.db

    (3) To use the existing database and read data from the client side, run
        > node config.js -test false

    (4) To use the existing database and populate it with test data, run
        > node config.js -test true


    Warning: DO NOT EDIT THIS FILE. DO NOT EDIT ANY .ENV FILES.

    Note:
        - If you do not specify a database file, this script checks that the default database file
        exists and prints an error message if it does not. This does not prevent you from going ahead
        and running the server without a database file.         
*/

const { Database } = require("./Database/db_interface.js");
const fs = require('node:fs');
const process = require('node:process');

// Global variable default values
let DATABASE_FILENAME = "rdgDatabase.db";
let TEST_MODE = true;

// Accepted command line flags
const DB_FLAG = '-db';
const TEST_FLAG = '-test';


/************** PROCESS DATABASE FLAG ***************************/
let index = process.argv.indexOf(DB_FLAG);

// no database filename specified
if (index == -1) {
    console.log(`No ${DB_FLAG} flag specified.`);
    console.log(`Checking if default database file (${DATABASE_FILENAME}) exists...`)
    if (fs.existsSync(DATABASE_FILENAME)) {
        console.log(`File exists: Application will use database file ${DATABASE_FILENAME}`);
    }
    else {
        console.log(`WARNING: Default database file ${DATABASE_FILENAME} does not exist!`);
    }
}
// a database filename is specified
else if (index + 1 < process.argv.length) {
    let candidateFileName = process.argv[index + 1];
    if (candidateFileName !== DB_FLAG && candidateFileName !== TEST_FLAG) {
        DATABASE_FILENAME = process.argv[index + 1];
    }
    else {
        console.log(`ERROR: Missing database filename...using default filename ${DATABASE_FILENAME}`);
    }
    console.log(`Creating new database file ${DATABASE_FILENAME}`);
    let db = new Database(DATABASE_FILENAME, "./database/database_schema.sql");
    db.close();
}

/************** PROCESS TEST MODE FLAG ***************************/
index = process.argv.indexOf(TEST_FLAG);
if (index == -1) {
    console.log(`No ${TEST_FLAG} flag specified.`);
    console.log('Running the application in test mode. The database will be populated with test data.')
}
else if (index + 1 < process.argv.length) {
    if (process.argv[index + 1] === "true") {
        console.log('Running application in test mode.');
        TEST_MODE = true;
    }
    if (process.argv[index + 1] === "false") {
        console.log('Running application in production mode.');
        TEST_MODE = false;
    }
}


/************** READ IN OTHER ENVIRONMENT VARIABLES ***************************/
let data = undefined;
try {
    data = fs.readFileSync('.env.production.local', 'utf8').split('\n');
}
catch (err) {
    console.log(err);
    console.log('Unable to open file .env.production.local');
}


/************** ADD USER-SET ENVIRONMENT VARIABLES ***************************/
data.push(`DATABASE_FILENAME="${DATABASE_FILENAME}"`);
data.push(`TEST_MODE=${TEST_MODE}`);


/************** WRITE ALL ENVIRONMENT VARIABLES TO FILE ***************************/
try {
    let contents = data.join('\n');
    fs.writeFileSync('.env', contents);
}
catch (err) {
    console.error(err);
}
